### ISSUE TITLE
Executing `:ProjectMgr` after install semi-fails

### ISSUE THREAD

**Issue by miversen33** [charludo/projectmgr.nvim#4] opened 2022-08-09 19:26 UTC
After following the installation steps on [here](https://github.com/charludo/projectmgr.nvim#-installation) (and manually installing the headers for sqlite3), I was able to successfully install ProjectMgr, however running the general command `:ProjectMgr` provides the following error
```lua
E5108: Error executing lua no such table: projects
stack traceback:
        [C]: in function 'nrows'
        ...cker/start/projectmgr.nvim/lua/projectmgr/db_adapter.lua:30: in function 'get_projects'
        ...k/packer/start/projectmgr.nvim/lua/projectmgr/window.lua:98: in function 'update_view'
        ...k/packer/start/projectmgr.nvim/lua/projectmgr/window.lua:115: in function 'open_window'
        [string ":lua"]:1: in main chunk
```

Note: after acknowledging the error, the floating window appears (with no contents, which makes sense as I haven't added any projects yet).

**Comment by zackartz** [comment] 2022-08-09 19:29
same here

**Comment by charludo** [comment] 2022-08-09 19:40
Oh shoot, that's not great.

Are you able to create projects (press `a` in the window)?

I'll look into it and push a fix tomorrow morning (it's night here), as a workaround you could copy the first SQL statement from `prepare_db()` in `db_adapter.lua` and create the table yourself.

Really sorry about this.

**Comment by miversen33** [comment] 2022-08-09 19:45
@charludo  no problem! I can walk through the setup of a project (pressing `a`), however it fails to save with the same error. My guess is your code is looking for a nonexistent table (as you eluded to). I am in no rush to use this, when you get a patch pushed out lemme know and I will try it again :)

**Comment by charludo** [comment] 2022-08-09 19:47
Nevermind, looks like lsqlite3's `nrows` returns nil rather than an empty table, so iterating over it fails.

You should be able to create a project in the window, then the issue should disappear. (Fix still coming in the morning.)

**Comment by charludo** [comment] 2022-08-09 19:54
Oh, quick question: is this happening on Windows or on Linux?

**Comment by miversen33** [comment] 2022-08-09 19:57
> Oh, quick question: is this happening on Windows or on Linux?

OS Info: Ubuntu 20.04.4 LTS
Neovim Info:
```
NVIM v0.8.0-dev+494-ge2f9d0332
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az21-224

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"
```

I apologize, I should have included that in the initial issue

**Comment by charludo** [comment] 2022-08-09 20:00
Nah, my bad for not having a template :D

**Comment by charludo** [comment] 2022-08-10 06:24
Unfortunately, I'm not able to reproduce the issue, even with a fresh install, which is kinda strange.

@zackartz did you also install the sqlite3 headers manually, just like @miversen33 did?

I'm asking because initially, I did use [lua-ljsqlite3](https://github.com/stepelu/lua-ljsqlite3) in the project, which unfortunately slightly deviates from [lsqlite3](https://luarocks.org/modules/dougcurrie/lsqlite3) - specifically, the `nrow` function causing errors here does not exist.

**Comment by zackartz** [comment] 2022-08-10 07:22
Hey! 

I am using Arch Linux with the `sqlite` package installed, and here is my packer configuration (w/ NvChad)
```lua
  ["charludo/projectmgr.nvim"] = {
    rocks = {'lsqlite3'},
  },
```
when I ran PackerSync everything installed properly with no errors.

**Comment by Dax89** [comment] 2022-08-10 08:17
I don't know if it's useful, but:
It says that the sqlite db is not setup yet, so I have called `require("projectmgr").setup()` (like other plugins) in my neovim configuration which by looking at the source code it creates the `projects` table if not exists and everything looks fine!


PS: Very nice plugin btw!

**Comment by charludo** [comment] 2022-08-10 08:18
Thank you for posting your config, @zackartz - the issue was that previously, not having a custom config (and therefore not calling the `setup` function) wouldn't add the autocommands resposnible for calling the startup function, which among other things ensures the database is set up properly.

Should be fixed now!

**Closed** 2022-08-10 08:17 UTC
Labels: bug

**Comment by charludo** [comment] 2022-08-10 08:20
@Dax89 yep, that was exactly it. Moved the augroup to the plugins `projectmgr.vim` file, now setup should be called automatically.

Also, thanks!
