### ISSUE TITLE
Cursor position outside error 

### ISSUE THREAD

**Issue by bmorashad** [charludo/projectmgr.nvim#1] opened 2022-06-21 05:45 UTC
Below error occurs when executing :ProjectMgr,

```
E5108: Error executing lua ...ack/packer/start/projectmgr.nvim/lua/projectmgr/init.lua:150: Cursor position outside buffer
stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        ...ack/packer/start/projectmgr.nvim/lua/projectmgr/init.lua:150: in function 'show_selection'
        [string ":lua"]:1: in main chunk
 ```

However it does open the _Projects_ window, and the add keybinding works. But the project doesn't get added

**Comment by charludo** [comment] 2022-06-21 07:35
Hi, thanks for opening the issue.

Looks like this was caused by the projects-table initially being empty. Should be fixed now.

**Closed by charludo** 2022-06-21 07:35 UTC

**Comment by bmorashad** [comment] 2022-06-21 07:42
Hi, damn that was so quick, thanks!
Awesome project, minimal & simple! and something I was looking for

**Comment by charludo** [comment] 2022-06-21 07:52
Always nice when a project is useful to other people! :D
Let me know if there are additional features you´d like to see implemented.
